### ISSUE TITLE
create server with snapshot

### ISSUE THREAD

**Issue by ninja71-mn** [cp6/Vultr-API-PHP-class#1]
hi
I need create a server with snapshot
but get code 400
with os do not have any problem
please help me.
thank you.

**Comment by cp6** [comment]
Thanks, fixed [here](https://github.com/cp6/Vultr-API-PHP-class/commit/dc85e227a7953baa83a33f1804ec51a9ad9951fd#diff-a0a812dd5af8851e62fd825f892b97364359397705d47df17409f86fe3ee4853)

```
//Create instance from snapshot:
$vultr->serverCreateDC('syd');
$vultr->serverCreatePlan('vc2-2c-4gb');
$vultr->serverCreateType('SNAPSHOT', 'YQrb72d9-ded9-4f68-a5cg-7d4f96a534de');
$vultr->serverCreateLabel('Created with API');
echo $vultr->serverCreate();
```
