### ISSUE TITLE
update instance problem

### ISSUE THREAD

**Issue by ninja71-mn** [cp6/Vultr-API-PHP-class#2]
hi
sorry i have another problem with instanceUpdate function.
this response is 202, but No changes will be made.
i use this function to update an instance.
    public function update($subid)
    {
        $this->vultr->setSubid($subid);
        $values=[
            "label"=>"label-test",
        ];
        $ff=$this->vultr->instanceUpdate($values);
        die(print_r($ff));
    }

**Comment by ninja71-mn** [comment]
I check all of the function with PATCH type, They have a similar problem

**Comment by cp6** [comment]
Fixed [here](https://github.com/cp6/Vultr-API-PHP-class/commit/26785e97db9d8f305a2421a26ecac488dcd2462d). 

Apologies.

```php
$vultr->setSubid('54dabafd-ec68-4811-b418-f649480bg972');
$vultr->instanceUpdate(["label" => "Updated label with API"]);
```
